// src/_components/TogetherWeStand/Artist.tsx
import React from 'react';
import { AiOutlineTwitter } from 'react-icons/ai';
import { FaPaintBrush, FaCalendarAlt, FaDiscord } from 'react-icons/fa';
import { Drop, drops } from '_content/tws';

const Artist = (props: ArtistProps) => {
	const images: any = [
		{
			src: "/images/tws/" + props.drop.piece.path,
			title: props.drop.piece.title,
			content: ""
		}
	]
	return (
		<section className={styles.container}>
			<h1 className={styles.heading}>{props.drop.artist}</h1>
			<h2 className={`text-center ${styles.subsectionHeading}`}>"{props.drop.piece.title}"</h2>
			<div className='grid grid-cols-1 mb-8'>
			<div>
				{props.drop.piece.released ? 
					(
						<img src={`/images/tws/${props.drop.piece.path}`} />
					)
					:
					(
						<img src={`/images/tws/${props.drop.piece.teaserPath}`} />
					)
				}
				</div>
				<div className='grid grid-cols-1 md:grid-cols-3 mb-8'>
					<div className='flex justify-center items-center text-gray-500 gap-x-2'>
						<FaPaintBrush size={14} />
						<a href={props.drop.portfolio}>Portfolio</a>
					</div>
					{props.drop.twitter && (
						<div className='flex justify-center items-center text-gray-500 gap-x-2'>
							<AiOutlineTwitter size={14} />
							<a href={`https://twitter.com/${props.drop.twitter}`}>{props.drop.twitter}</a>
						</div>
					)}
					{props.drop.discord && (
						<div className='flex justify-center items-center text-gray-500 gap-x-2'>
							<FaDiscord size={14} />
							{props.drop.discord}
						</div>
					)}
				</div>
				<div>
				{props.drop.copy && props.drop.copy.map((copy: string) => (
					<p className={styles.subsectionParagraph} dangerouslySetInnerHTML={{__html: (copy)}}></p>
				))}
				</div>
			</div>
			{props.drop.qa && (
				<h2 className={styles.subsectionHeading}>Q &amp; A</h2>
			)}
			{props.drop.qa && props.drop.qa.map((qa: [string, string]) => (
				<div>
					<div className="rounded bg-pink-500 bg-opacity-10 p-4 my-4">
						<p className={styles.subsectionQuestion}>{qa[0]}</p>
						<p className={`${styles.subsectionAnswer} mb-0`}>"{qa[1]}"</p>
					</div>
				</div>
			))}
		</section>
	);
};

type ArtistProps = {
	drop: Drop;
};

export default Artist;

const styles = {
	container:
		'max-w-screen-lg w-full mx-auto my-24 md:my-48 px-12 md:px-6 font-display',
	heading: 'text-4xl md:text-6xl text-center',
	subsectionHeading: 'text-2xl md:text-4xl mb-6',
	subsectionParagraph:
	'tracking-wider font-display w-full opacity-80 mt-4 mb-4 md:mb-8 text-gray-300',
	subsectionQuestion:
	'tracking-wider font-display w-full',
	subsectionAnswer:
	'tracking-wider font-display w-full opacity-80 my-4 text-gray-300 pl-4 border-l-2',
	dropsContainer:
		'grid grid-cols-1 mb-4',
};

// src/lib/TogetherWeStand/Artist.svelte
<script>
// @ts-nocheck

    import Navigation from "$lib/Navigation/Navigation.svelte";
    import Fa from 'svelte-fa/src/fa.svelte';
    import { faPaintBrush } from '@fortawesome/free-solid-svg-icons/index.js';
    import { faDiscord, faTwitter } from '@fortawesome/free-brands-svg-icons/index.js';
    import "$lib/css/global.css";
    import BackToTop from '$lib/BackToTop.svelte';

    export let artist = "";
    export let twitter = "";
    export let portfolio = "";
    export let discord = "";
    export let piecePath = "";
    export let pieceTeaserPath = "";
    export let pieceTitle = "";
    export let pieceReleased = false;
    export let copy = [];
    export let qa = [];

</script>


<Navigation />
<section class="container">
    <h1 class="heading" style="text-align: center">{artist}</h1>
    <h2 class="subsectionHeading" style="text-align: center;">"{pieceTitle}"</h2>
    <div class="dropContainer" style="gap: 0.5rem;">
        <div>
            {#if pieceReleased}
                <img style="max-width: 100%" src={`/images/tws/${piecePath}`} alt="TWS art piece"/>
            {:else}
                <img style="max-width: 100%" src={`/images/tws/${pieceTeaserPath}`} alt="TWS art piece teaser"/>
            {/if}
        </div>
        <div class="tws-info">
            <div>
                <Fa icon={faPaintBrush} size="sm" />
                <a href={portfolio}>Portfolio</a>
            </div>
            <div>
                <Fa icon={faTwitter} size="sm" />
                <a href={`https://twitter.com/${twitter}`}>{twitter}</a>
            </div>
            <div>
                <Fa icon={faDiscord} size="sm" />
                {discord}
            </div>
        </div>
        <div class="infos">
            {#if copy.length != 0}
                {#each copy as copyElem}
                    {#if copyElem[0] == "readMore"}
                        <p class="readMore">{@html copyElem[1]}</p>
                    {:else if copyElem[0] == "h1"}
                        <p class="title">{@html copyElem[1]}</p>
                    {:else}
                        <p class="subsectionParagraph">{@html copyElem[0]}</p>
                    {/if}
                {/each}
            {/if}
        </div>
        {#if qa.length != 0}
            <h2 class="subsectionHeading">Q &amp; A</h2>
            {#each qa as qaElem}
                <div>
                    <div class="qa">
                        <p class="subsectionQuestion">{qaElem[0]}</p>
                        <p class="subsectionAnswer" style="margin-bottom: 0px;">{qaElem[1]}</p>
                    </div>
                </div>
            {/each}
        {/if}
    </div>
</section>
<BackToTop />



<style>
    a {
        color: inherit;
    }

    .infos {
        margin-top: 3rem;
    }

    .tws-info {
        display: flex;
        align-items: center;
        justify-content: space-around;
        color: var(--purple-white);
    }

    .subsectionParagraph {
        text-align: justify;
        line-height: 1.5rem;
        letter-spacing: 0.05rem;
        width: 100%;
        opacity: 0.8;
        margin-top: 0.5rem;
        color: var(--purple-white);
    }

    .title {
        color: var(--white-purple);
    }

    .readMore {
        border-left: 2px var(--whiter-purple) solid;
        background-color: rgb(31 6 56 / 1);
        padding: 0.5rem;
        padding-left: 1rem;
        border-radius: 0.25rem;
        margin-bottom: 4rem;
        color: var(--whiter-purple);
    }

    .subsectionQuestion {
        width: 100%;
        margin-top: 0rem;
        letter-spacing: 0.05em;
        color: var(--whiter-purple);
    }

	.subsectionAnswer {
        width: 100%;
        margin-top: 1rem;
        margin-bottom: 1rem;
        letter-spacing: 0.05rem;
        color: var(--purple-white);
        padding-left: 1rem;
        border-left: 2px currentColor solid;
    }

    .qa {
        border-radius: 0.25rem;
        background-color: rgb(31 6 56 / 1);
        padding: 1rem;
        margin-top: 1rem;
        margin-bottom: 1rem;
    }

@media (max-width: 500px) {
    .tws-info {
        font-size: 0.5rem;
    }
}
</style>
